name: Build and Upload Container

on:
  release:
    types: [prereleased]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  APP_NAME: PingPong

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Buildah Action
        id: build-image
        run: |
          podman build . -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$GITHUB_SHA
          podman save ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$GITHUB_SHA > ./${{ env.APP_NAME }}.container.tar
      - name: Upload Container
        run: gh release upload ${{ github.ref_name }} ./${{ env.APP_NAME }}.container.tar
