name: Build and Upload Windows Executable

on:
  release:
    types: [prereleased]

jobs:
  build:
    runs-on: macos-12
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
      APP_NAME: PingPong
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm ci
        working-directory: ./frontend
      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip" # caching pip dependencies
      - name: Install Python Dependencies
        run: python -m venv .venv && .venv/Scripts/activate && pip install -r requirements.txt
      - name: Build Executable with pyinstaller
        run: source .venv/bin/activate && pyinstaller -n ${{ APP_NAME }} --add-data frontend/dist/:frontend/dist/ --windowed --icon frontend/public/favicon.ico --onefile app.py
      - name: Install create-dmg
        run: brew install create-dmg
      - name: Build dmg
        run: |
          mkdir -p dist/dmg
          rm -rf dist/dmg/*
          cp -r dist/${{ APP_NAME }}.app dist/dmg/
          create-dmg \
            --volname ${{ APP_NAME }} \
            --volicon "frontend/public/favicon.ico" \
            --window-pos 200 120 \
            --window-size 600 300 \
            --icon-size 100 \
            --icon "${{ APP_NAME }}.app" 175 120 \
            --hide-extension "#{{ APP_NAME }}.app" \
            --app-drop-link 425 120 \
            "dist/${{ APP_NAME }}.dmg" \
            "dist/dmg/"
      - name: Upload dmg
        run: gh release upload ${{ github.ref_name }} dist/${{ APP_NAME }}.dmg
