name: Build Container

on:
  release:
    types: [prereleased]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Buildah Action
        id: build-image
        run: |
          podman build -f ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$GITHUB_SHA
          mkdir -p /srv/app
          podman save ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$GITHUB_SHA > /srv/app/ping-pong-container.tar
      - name: Upload Container
        run: gh release upload ${{ github.ref_name }} /srv/app/ping-pong-container.tar
